# Start AeroSpace at login
start-at-login = true

# run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
after-login-command = []

# run after AeroSpace startup.
# 'after-startup-command' runs after 'after-login-command'
after-startup-command = []

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
# on-focus-changed = ['move-mouse window-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

# 'main' binding mode declaration, must be always presented
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.main.binding]

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-backtick = 'exec-and-forget ~/scripts/show-workspaces.sh'

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'
    alt-left = 'focus-monitor left'
    alt-down = 'focus-monitor down'
    alt-up = 'focus-monitor up'
    alt-right = 'focus-monitor right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'
    alt-shift-left = "move-workspace-to-monitor left"
    alt-shift-down = "move-workspace-to-monitor down"
    alt-shift-up = "move-workspace-to-monitor up"
    alt-shift-right = "move-workspace-to-monitor right"

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    # workspaces
    alt-1 = 'workspace 1'
    alt-shift-1 = 'move-node-to-workspace 1'

    alt-2 = 'workspace 2'
    alt-shift-2 = 'move-node-to-workspace 2'

    alt-3 = 'workspace 3'
    alt-shift-3 = 'move-node-to-workspace 3'

    alt-4 = 'workspace 4'
    alt-shift-4 = 'move-node-to-workspace 4'

    alt-5 = 'workspace 5'
    alt-shift-5 = 'move-node-to-workspace 5'

    alt-6 = 'workspace 6'
    alt-shift-6 = 'move-node-to-workspace 6'

    alt-7 = 'workspace 7'
    alt-shift-7 = 'move-node-to-workspace 7'

    alt-8 = 'workspace 8'
    alt-shift-8 = 'move-node-to-workspace 8'

    alt-9 = 'workspace 9'
    alt-shift-9 = 'move-node-to-workspace 9'

    alt-a = 'workspace A'
    alt-shift-a = 'move-node-to-workspace A'

    alt-b = 'workspace B'
    alt-shift-b = 'move-node-to-workspace B'

    alt-c = 'workspace Calendar'
    alt-shift-c = 'move-node-to-workspace Calendar'

    alt-d = 'workspace D'
    alt-shift-d = 'move-node-to-workspace D'

    alt-e = 'workspace Email'
    alt-shift-e = 'move-node-to-workspace Email'

    alt-f = 'workspace F'
    alt-shift-f = 'move-node-to-workspace F'

    alt-g = 'workspace Git'
    alt-shift-g = 'move-node-to-workspace Git'

    alt-i = 'workspace I'
    alt-shift-i = 'move-node-to-workspace I'

    alt-m = 'workspace M'
    alt-shift-m = 'move-node-to-workspace M'

    alt-n = 'workspace N'
    alt-shift-n = 'move-node-to-workspace N'

    alt-o = 'workspace Obsidian'
    alt-shift-o = 'move-node-to-workspace Obsidian'

    alt-p = 'workspace P'
    alt-shift-p = 'move-node-to-workspace P'

    alt-q = 'workspace Q'
    alt-shift-q = 'move-node-to-workspace Q'

    alt-r = 'workspace R'
    alt-shift-r = 'move-node-to-workspace R'

    alt-s = 'workspace S'
    alt-shift-s = 'move-node-to-workspace S'

    alt-t = 'workspace Temporary'
    alt-shift-t = 'move-node-to-workspace Temporary'

    alt-u = 'workspace U'
    alt-shift-u = 'move-node-to-workspace U'

    alt-v = 'workspace VS_Code'
    alt-shift-v = 'move-node-to-workspace VS_Code'

    alt-w = 'workspace W'
    alt-shift-w = 'move-node-to-workspace W'

    alt-x = 'workspace X'
    alt-shift-x = 'move-node-to-workspace X'

    alt-y = 'workspace Y'
    alt-shift-y = 'move-node-to-workspace Y'

    alt-z = 'workspace Zotero'
    alt-shift-z = 'move-node-to-workspace Zotero'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    alt-tab = 'workspace-back-and-forth'
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
    # You can uncomment the following lines to open up terminal with alt + enter shortcut
    # (like in i3)
    # alt-enter = '''exec-and-forget osascript -e '
    # tell application "Terminal"
    #     do script
    #     activate
    # end tell'
    # '''

    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    alt-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']
    w = [
        'exec-and-forget open -g -a Calendar',
        'exec-and-forget open -g -a Reminders',
        'exec-and-forget open -g -a "Microsoft Outlook"',
        'exec-and-forget open -g -a Obsidian',
        'exec-and-forget open -g -a "Visual Studio Code"',
        'exec-and-forget open -g -a Zotero',
        'mode main'        
    ]
    q = [
        'exec-and-forget killall Calendar',
        'exec-and-forget killall Reminders',
        'exec-and-forget killall "Microsoft Outlook"',
        'exec-and-forget killall Obsidian',#'exec-and-forget osascript -e \\'quit app "Visual Studio Code"\\'',
        'exec-and-forget killall zotero',
        'mode main'
    ]

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']


# Apple default apps 
[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'move-node-to-workspace Calendar'

[[on-window-detected]]
if.app-id = 'com.apple.calculator'
run = 'layout floating'

# [[on-window-detected]]  # not necessary as this is by default
# if.app-id = 'com.apple.FaceTime'
# run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.findmy'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.reminders'
run = 'move-node-to-workspace Calendar'

# [[on-window-detected]] # not necessary as this is by default
# if.app-id = 'com.apple.ScreenContinuity' 
# run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.github.GitHubClient'
run = 'move-node-to-workspace Git'

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

# third-party apps
[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace Obsidian'

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = 'move-node-to-workspace Email'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace VS_Code'

[[on-window-detected]]
if.app-id = 'org.zotero.zotero'
run = 'move-node-to-workspace Zotero'
