#!/usr/bin/env bash

# Useful links
# project home:       https://github.com/FelixKratz/SketchyBar
# config reference:   https://felixkratz.github.io/SketchyBar/config

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

source "$CONFIG_DIR/colors.sh"

########################################################
## different layouts for single and multiple monitors ##
########################################################
MONITOR_COUNT=$(system_profiler SPDisplaysDataType | grep -c "Resolution")

#### SketchyBar Configuration ####
source "$CONFIG_DIR/defaults.sh"

#### SketchyBar Initialization ####
source "$CONFIG_DIR/bar.sh"

##### Mission Control Space Indicators #####
# aerospace related events
sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_monitor_change
sketchybar --add event aerospace_move_node
sketchybar --add event aerospace_mode_change

##### Left Items #####
source "$ITEM_DIR/header.sh"

# single monitor
if (( MONITOR_COUNT == 1 )); then
  source "$ITEM_DIR/spaces_single.sh"  
fi

# multiple monitors
if (( MONITOR_COUNT > 1 )); then
  source "$ITEM_DIR/spaces_multiple.sh"
  #source "$ITEM_DIR/spaces_single.sh"  
fi

source "$ITEM_DIR/front_app.sh"

##### Right Items ##### 
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"
             
#####  Groups #####

# sketchybar --add bracket spaces '/space\..*/' \
#            --set spaces background.color=$YELLOW \
#               background.corner_radius=10 \
#               background.height=30

 #  --add item volume right \
          #  --set volume script="$PLUGIN_DIR/volume.sh" \
          #  --subscribe volume volume_change \

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
